--------------------------------------------------------
-- Archivo creado  - lunes-noviembre-14-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BARRIO
--------------------------------------------------------

  CREATE TABLE "BARRIO" 
   (	"ID_BARRIO" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"RELA_LOCALIDAD" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTACTO
--------------------------------------------------------

  CREATE TABLE "CONTACTO" 
   (	"ID_CONTACTO" NUMBER(10,0), 
	"RELA_TCONTACTO" NUMBER(10,0), 
	"RELA_PERSONA" NUMBER(10,0), 
	"VALOR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DIRECCION_PER
--------------------------------------------------------

  CREATE TABLE "DIRECCION_PER" 
   (	"ID_DIRECCION" NUMBER(10,0), 
	"CALLE" VARCHAR2(20 BYTE), 
	"NUMERO" NUMBER(10,0), 
	"SECTOR" VARCHAR2(10 BYTE), 
	"MANZANA" VARCHAR2(10 BYTE), 
	"CASA" VARCHAR2(10 BYTE), 
	"TORRE" VARCHAR2(10 BYTE), 
	"PISO" VARCHAR2(5 BYTE), 
	"DEPTO" VARCHAR2(5 BYTE), 
	"RELALA_PERSONA" NUMBER(10,0), 
	"RELA_BARRIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOCALIDAD
--------------------------------------------------------

  CREATE TABLE "LOCALIDAD" 
   (	"ID_LOCALIDA" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"RELA_PROVINCIA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAIS
--------------------------------------------------------

  CREATE TABLE "PAIS" 
   (	"ID_PAIS" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA_CAB
--------------------------------------------------------

  CREATE TABLE "PERSONA_CAB" 
   (	"ID_PERSONA" NUMBER(10,0), 
	"PER_NOMBRES" VARCHAR2(100 BYTE), 
	"PER_APELLIDOS" VARCHAR2(100 BYTE), 
	"DNI" NUMBER(8,0), 
	"PER_CUILT" NUMBER(11,0), 
	"SEXO" NUMBER(1,0), 
	"ESTADO_CIVIL" NUMBER(1,0), 
	"F_NACIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PERSONA_CAB"."SEXO" IS '"1 MASCULINO, 0 FEMENINO"';
   COMMENT ON COLUMN "PERSONA_CAB"."ESTADO_CIVIL" IS '"0 SOLTERO/A, 1 CASADO/A,  2 DIVORCIADO/A, 3 VIUDO/A, 4NO DEFINIDO"';
--------------------------------------------------------
--  DDL for Table PROVINCIA
--------------------------------------------------------

  CREATE TABLE "PROVINCIA" 
   (	"ID_PROVINCIA" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"CODIGO_POSTAL" NUMBER(10,0), 
	"RELA_PAIS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_DE_CONTACTO
--------------------------------------------------------

  CREATE TABLE "TIPO_DE_CONTACTO" 
   (	"ID_TCONTACTO" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence S_PERSONA
--------------------------------------------------------

   CREATE SEQUENCE  "S_PERSONA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Index IDX_CUIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_CUIL" ON "PERSONA_CAB" ("PER_CUILT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROVINCIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROVINCIA_PK" ON "PROVINCIA" ("ID_PROVINCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONTACTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTACTO_PK" ON "CONTACTO" ("ID_CONTACTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERSONA_PK" ON "PERSONA_CAB" ("ID_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DIRECCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DIRECCION_PK" ON "DIRECCION_PER" ("ID_DIRECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOCALIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOCALIDAD_PK" ON "LOCALIDAD" ("ID_LOCALIDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PAIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAIS_PK" ON "PAIS" ("ID_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BARRIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BARRIO_PK" ON "BARRIO" ("ID_BARRIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_DE_CONTACTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIPO_DE_CONTACTO_PK" ON "TIPO_DE_CONTACTO" ("ID_TCONTACTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TGR_INS_PERSONA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TGR_INS_PERSONA" 
BEFORE INSERT ON PERSONA_CAB 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  SELECT S_PERSONA.NEXTVAL INTO :NEW.ID_PERSONA FROM DUAL;
END;
/
ALTER TRIGGER "TGR_INS_PERSONA" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVINCIA
--------------------------------------------------------

  ALTER TABLE "PROVINCIA" MODIFY ("RELA_PAIS" NOT NULL ENABLE);
  ALTER TABLE "PROVINCIA" ADD CONSTRAINT "PROVINCIA_PK" PRIMARY KEY ("ID_PROVINCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROVINCIA" MODIFY ("CODIGO_POSTAL" NOT NULL ENABLE);
  ALTER TABLE "PROVINCIA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PROVINCIA" MODIFY ("ID_PROVINCIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTACTO
--------------------------------------------------------

  ALTER TABLE "CONTACTO" ADD CONSTRAINT "CONTACTO_PK" PRIMARY KEY ("ID_CONTACTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTACTO" MODIFY ("RELA_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "CONTACTO" MODIFY ("RELA_TCONTACTO" NOT NULL ENABLE);
  ALTER TABLE "CONTACTO" MODIFY ("ID_CONTACTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_DE_CONTACTO
--------------------------------------------------------

  ALTER TABLE "TIPO_DE_CONTACTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "TIPO_DE_CONTACTO" ADD CONSTRAINT "TIPO_DE_CONTACTO_PK" PRIMARY KEY ("ID_TCONTACTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TIPO_DE_CONTACTO" MODIFY ("ID_TCONTACTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIRECCION_PER
--------------------------------------------------------

  ALTER TABLE "DIRECCION_PER" MODIFY ("RELA_BARRIO" NOT NULL ENABLE);
  ALTER TABLE "DIRECCION_PER" MODIFY ("DEPTO" NOT NULL ENABLE);
  ALTER TABLE "DIRECCION_PER" MODIFY ("PISO" NOT NULL ENABLE);
  ALTER TABLE "DIRECCION_PER" MODIFY ("TORRE" NOT NULL ENABLE);
  ALTER TABLE "DIRECCION_PER" MODIFY ("CASA" NOT NULL ENABLE);
  ALTER TABLE "DIRECCION_PER" MODIFY ("MANZANA" NOT NULL ENABLE);
  ALTER TABLE "DIRECCION_PER" MODIFY ("SECTOR" NOT NULL ENABLE);
  ALTER TABLE "DIRECCION_PER" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "DIRECCION_PER" MODIFY ("CALLE" NOT NULL ENABLE);
  ALTER TABLE "DIRECCION_PER" MODIFY ("RELALA_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "DIRECCION_PER" ADD CONSTRAINT "DIRECCION_PK" PRIMARY KEY ("ID_DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DIRECCION_PER" MODIFY ("ID_DIRECCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCALIDAD
--------------------------------------------------------

  ALTER TABLE "LOCALIDAD" ADD CONSTRAINT "LOCALIDAD_PK" PRIMARY KEY ("ID_LOCALIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LOCALIDAD" MODIFY ("RELA_PROVINCIA" NOT NULL ENABLE);
  ALTER TABLE "LOCALIDAD" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LOCALIDAD" MODIFY ("ID_LOCALIDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BARRIO
--------------------------------------------------------

  ALTER TABLE "BARRIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "BARRIO" MODIFY ("RELA_LOCALIDAD" NOT NULL ENABLE);
  ALTER TABLE "BARRIO" ADD CONSTRAINT "BARRIO_PK" PRIMARY KEY ("ID_BARRIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BARRIO" MODIFY ("ID_BARRIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA_CAB
--------------------------------------------------------

  ALTER TABLE "PERSONA_CAB" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("ID_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PERSONA_CAB" MODIFY ("F_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "PERSONA_CAB" MODIFY ("ESTADO_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "PERSONA_CAB" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "PERSONA_CAB" MODIFY ("PER_APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "PERSONA_CAB" MODIFY ("PER_NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "PERSONA_CAB" MODIFY ("ID_PERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAIS
--------------------------------------------------------

  ALTER TABLE "PAIS" ADD CONSTRAINT "PAIS_PK" PRIMARY KEY ("ID_PAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PAIS" MODIFY ("ID_PAIS" NOT NULL ENABLE);
  ALTER TABLE "PAIS" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BARRIO
--------------------------------------------------------

  ALTER TABLE "BARRIO" ADD CONSTRAINT "FK_LOCALIDAD_BARRIO" FOREIGN KEY ("RELA_LOCALIDAD")
	  REFERENCES "LOCALIDAD" ("ID_LOCALIDA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTACTO
--------------------------------------------------------

  ALTER TABLE "CONTACTO" ADD CONSTRAINT "FK_PERSONA_CONTACTO" FOREIGN KEY ("RELA_PERSONA")
	  REFERENCES "PERSONA_CAB" ("ID_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIRECCION_PER
--------------------------------------------------------

  ALTER TABLE "DIRECCION_PER" ADD CONSTRAINT "FK_DIRECCION_BARRIO" FOREIGN KEY ("RELA_BARRIO")
	  REFERENCES "BARRIO" ("ID_BARRIO") ENABLE;
  ALTER TABLE "DIRECCION_PER" ADD CONSTRAINT "FK_PERSONA_DIRECCION" FOREIGN KEY ("RELALA_PERSONA")
	  REFERENCES "PERSONA_CAB" ("ID_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCALIDAD
--------------------------------------------------------

  ALTER TABLE "LOCALIDAD" ADD CONSTRAINT "FK_PROVINCIA_LOCALIDAD" FOREIGN KEY ("RELA_PROVINCIA")
	  REFERENCES "PROVINCIA" ("ID_PROVINCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROVINCIA
--------------------------------------------------------

  ALTER TABLE "PROVINCIA" ADD CONSTRAINT "FK_PAIS_PROVINCIA" FOREIGN KEY ("RELA_PAIS")
	  REFERENCES "PAIS" ("ID_PAIS") ENABLE;
