--------------------------------------------------------
-- Archivo creado  - lunes-noviembre-14-2016   
--------------------------------------------------------
--------------------------------------------------------


  CREATE TABLE "PERSONA_SITIO" 
   (	"ID_PER_SITIO" NUMBER(10,0), 
	"RELA_PERSONA" NUMBER(10,0), 
	"RELA_SITIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROVINCIA
--------------------------------------------------------

  CREATE TABLE "RUBRO" 
   (	"ID_RUBRO" NUMBER(10,0), 
	"CODIGO" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"RELA_SITIO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SITIO_CAB
--------------------------------------------------------

  CREATE TABLE "SITIO_CAB" 
   (	"ID_SITIO" NUMBER(10,0), 
	"SITIO_NOMBRES" VARCHAR2(100 BYTE), 
	"F_ALTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SITIO_CONTACTO
--------------------------------------------------------

  CREATE TABLE "SITIO_CONTACTO" 
   (	"ID_SCONTACTO" NUMBER(10,0), 
	"RELA_TCONTACTO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SITIO_DIRECCION
--------------------------------------------------------

  CREATE TABLE "SITIO_DIRECCION" 
   (	"ID_DIRECCION" NUMBER(10,0), 
	"CALLE" VARCHAR2(20 BYTE), 
	"NUMERO" NUMBER(10,0), 
	"SECTOR" VARCHAR2(10 BYTE), 
	"MANZANA" VARCHAR2(10 BYTE), 
	"CASA" VARCHAR2(10 BYTE), 
	"TORRE" VARCHAR2(10 BYTE), 
	"PISO" VARCHAR2(10 BYTE), 
	"DEPTO" VARCHAR2(10 BYTE), 
	"RELA_BARRIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_CONTACTO
--------------------------------------------------------

  CREATE TABLE "TIPO_CONTACTO" 
   (	"ID_TIPOCONTACTO" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"VALOR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_RUBRO
--------------------------------------------------------

  CREATE TABLE "TIPO_RUBRO" 
   (	"ID_TIPORUBRO" NUMBER(10,0), 
	"CODIGO" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"RELA_RUBRO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence S_RUBRO
--------------------------------------------------------

   CREATE SEQUENCE  "S_RUBRO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_SITIO
--------------------------------------------------------

   CREATE SEQUENCE  "S_SITIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_TIPORUBRO
--------------------------------------------------------

   CREATE SEQUENCE  "S_TIPORUBRO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Index TIPO_RUBRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIPO_RUBRO_PK" ON "TIPO_RUBRO" ("ID_TIPORUBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONA_SITIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERSONA_SITIO_PK" ON "PERSONA_SITIO" ("ID_PER_SITIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BARRIO_PK
--------------------------------------------------------

    CREATE UNIQUE INDEX "SITIO_DIRECCION_PK" ON "SITIO_DIRECCION" ("ID_DIRECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_CONTACTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIPO_CONTACTO_PK" ON "TIPO_CONTACTO" ("ID_TIPOCONTACTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROVINCIA_PK
--------------------------------------------------------

   CREATE UNIQUE INDEX "RUBRO_PK" ON "RUBRO" ("ID_RUBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SITIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SITIO_PK" ON "SITIO_CAB" ("ID_SITIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TGR_INS_RUBRO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TGR_INS_RUBRO" 
BEFORE INSERT ON RUBRO 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  SELECT S_RUBRO.NEXTVAL INTO :NEW.ID_RUBRO FROM DUAL;
END;
/
ALTER TRIGGER "TGR_INS_RUBRO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TGR_INS_SITIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TGR_INS_SITIO" 
BEFORE INSERT ON SITIO_CAB 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  SELECT S_SITIO.NEXTVAL INTO :NEW.ID_SITIO FROM DUAL;
END;
/
ALTER TRIGGER "TGR_INS_SITIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TGR_INS_TIPORUBRO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TGR_INS_TIPORUBRO" 
BEFORE INSERT ON TIPO_RUBRO 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  SELECT S_TIPORUBRO.NEXTVAL INTO :NEW.ID_TIPORUBRO FROM DUAL;
END;
/
ALTER TRIGGER "TGR_INS_TIPORUBRO" ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_RUBRO
--------------------------------------------------------

  ALTER TABLE "TIPO_RUBRO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "TIPO_RUBRO" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "TIPO_RUBRO" ADD CONSTRAINT "TIPO_RUBRO_PK" PRIMARY KEY ("ID_TIPORUBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TIPO_RUBRO" MODIFY ("ID_TIPORUBRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITIO_DIRECCION
--------------------------------------------------------

  ALTER TABLE "SITIO_DIRECCION" ADD CONSTRAINT "SITIO_DIRECCION_PK" PRIMARY KEY ("ID_DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SITIO_DIRECCION" MODIFY ("ID_DIRECCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA_SITIO
--------------------------------------------------------

  ALTER TABLE "PERSONA_SITIO" ADD CONSTRAINT "PERSONA_SITIO_PK" PRIMARY KEY ("ID_PER_SITIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PERSONA_SITIO" MODIFY ("RELA_SITIO" NOT NULL ENABLE);
  ALTER TABLE "PERSONA_SITIO" MODIFY ("RELA_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "PERSONA_SITIO" MODIFY ("ID_PER_SITIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAIS
--------------------------------------------------------

    ALTER TABLE "TIPO_CONTACTO" ADD CONSTRAINT "TIPO_CONTACTO_PK" PRIMARY KEY ("ID_TIPOCONTACTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TIPO_CONTACTO" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "TIPO_CONTACTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "TIPO_CONTACTO" MODIFY ("ID_TIPOCONTACTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROVINCIA
--------------------------------------------------------

  
  ALTER TABLE "SITIO_CONTACTO" MODIFY ("ID_SCONTACTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITIO_CAB
--------------------------------------------------------

  ALTER TABLE "SITIO_CAB" MODIFY ("F_ALTA" NOT NULL ENABLE);
  ALTER TABLE "SITIO_CAB" ADD CONSTRAINT "SITIO_PK" PRIMARY KEY ("ID_SITIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SITIO_CAB" MODIFY ("SITIO_NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "SITIO_CAB" MODIFY ("ID_SITIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUBRO
--------------------------------------------------------

  ALTER TABLE "RUBRO" ADD CONSTRAINT "RUBRO_PK" PRIMARY KEY ("ID_RUBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RUBRO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "RUBRO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCALIDAD

--------------------------------------------------------

  ALTER TABLE "SITIO_DIRECCION" ADD CONSTRAINT "FK_SITIO_DIRECCION" FOREIGN KEY ("ID_DIRECCION")
	  REFERENCES "BARRIO" ("ID_BARRIO") ENABLE;
